apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-delete-task
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: {{.Release.Name}}-delete-task
  ports:
  - port: 80
    targetPort: 80
